/**
 * The non-negotiable anonymity gate (CLAUDE.md lines 159-173).
 *
 * This suite must pass before any commit. If a change makes it fail, the change
 * is wrong — do not edit this file to make it pass.
 *
 * Written generically on purpose: assertion 5 enumerates whatever admin routes
 * exist at the time it runs, so it gains coverage automatically as the app grows
 * and never needs editing.
 *
 * Run: npm run test:anonymity
 */
import pg from 'pg'
import { readdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { createSubmission } from '../src/lib/submissions'
import { hashReferenceCode } from '../src/lib/reference'

const client = new pg.Client({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
})

let failures = 0
let created: string | null = null

function check(n: number, label: string, ok: boolean, detail = '') {
  if (ok) {
    console.log(`  PASS  ${n}. ${label}`)
  } else {
    failures++
    console.error(`  FAIL  ${n}. ${label}${detail ? `\n        ${detail}` : ''}`)
  }
}

await client.connect()
console.log('\nAnonymity gate\n')

try {
  // ---------------------------------------------------------------------------
  // 1. A complaint with name/contact deliberately injected persists both NULL.
  // ---------------------------------------------------------------------------
  const { id, referenceCode } = await createSubmission({
    kind: 'complaint',
    category: 'Facilities',
    subject: 'ANONYMITY GATE PROBE',
    body: 'Automated test row. Safe to delete.',
    // Hostile input: a caller trying to attach identity to a complaint.
    name: 'Injected Name',
    contact: 'injected@example.com',
    revealName: true,
  })
  created = id

  const row = (
    await client.query('select * from public.submissions where id = $1', [id])
  ).rows[0]

  check(
    1,
    'complaint stores name and contact as NULL despite injection',
    row.name === null && row.contact === null,
    `got name=${JSON.stringify(row.name)} contact=${JSON.stringify(row.contact)}`
  )

  // ---------------------------------------------------------------------------
  // 2. No identity-bearing column exists anywhere on the table.
  // ---------------------------------------------------------------------------
  const cols: string[] = (
    await client.query(
      `select column_name from information_schema.columns
        where table_schema = 'public' and table_name = 'submissions'`
    )
  ).rows.map((r) => r.column_name)

  const forbidden = /(^|_)(ip|ipaddr|ip_address|user_agent|useragent|session|session_id|fingerprint|device|user_id|author_id)(_|$)/i
  const offenders = cols.filter((c) => forbidden.test(c))
  check(
    2,
    'no ip / user-agent / session / identity column on submissions',
    offenders.length === 0,
    `offending columns: ${offenders.join(', ')}`
  )

  // ---------------------------------------------------------------------------
  // 3. The anon role is refused on submissions.
  //    Tested by assuming the role in-session, which checks the actual grant
  //    rather than an HTTP status that could be 401 for unrelated reasons.
  // ---------------------------------------------------------------------------
  let anonBlocked = false
  let anonDetail = 'anon SELECT unexpectedly succeeded'
  try {
    await client.query('begin')
    await client.query('set local role anon')
    await client.query('select * from public.submissions limit 1')
  } catch (e) {
    // 42501 = insufficient_privilege
    anonBlocked = (e as { code?: string }).code === '42501'
    anonDetail = `expected SQLSTATE 42501, got ${(e as { code?: string }).code}: ${(e as Error).message}`
  } finally {
    await client.query('rollback')
  }
  check(3, 'anon role receives a permission error on submissions', anonBlocked, anonDetail)

  // ---------------------------------------------------------------------------
  // 4. The plaintext reference code is absent from the row; only its hash is stored.
  // ---------------------------------------------------------------------------
  const serialized = JSON.stringify(row)
  const bare = referenceCode.replace('SV-', '')
  const leaked = serialized.includes(referenceCode) || serialized.includes(bare)
  const hashStored = row.ref_hash === hashReferenceCode(referenceCode)
  check(
    4,
    'reference code stored only as SHA-256, plaintext absent from row',
    !leaked && hashStored,
    leaked ? 'plaintext code found in the stored row' : 'ref_hash does not match SHA-256 of the code'
  )

  // ---------------------------------------------------------------------------
  // 5. Every /api/admin/* route rejects a member-level session.
  //    Enumerates the route tree, so new admin routes are covered automatically.
  // ---------------------------------------------------------------------------
  const adminDir = join('src', 'app', 'api', 'admin')
  const adminRoutes: string[] = []
  if (existsSync(adminDir)) {
    const walk = async (dir: string) => {
      for (const ent of await readdir(dir, { withFileTypes: true })) {
        const p = join(dir, ent.name)
        if (ent.isDirectory()) await walk(p)
        else if (/^route\.(ts|js)$/.test(ent.name)) adminRoutes.push(p)
      }
    }
    await walk(adminDir)
  }

  if (adminRoutes.length === 0) {
    console.log(
      '  ----  5. no /api/admin/* routes exist yet — assertion is VACUOUS, not proven.'
    )
    console.log(
      '        It gains teeth automatically when the admin slice adds routes.'
    )
  } else {
    const base = process.env.TEST_BASE_URL ?? 'http://localhost:3000'
    let allRejected = true
    const bad: string[] = []
    for (const file of adminRoutes) {
      const url =
        base +
        '/' +
        file
          .replace(/\\/g, '/')
          .replace(/^src\/app/, '')
          .replace(/\/route\.(ts|js)$/, '')
      try {
        // A member-level cookie: gated in, but not an admin.
        const res = await fetch(url, { headers: { cookie: 'sof_role=member' } })
        if (res.status !== 401 && res.status !== 403) {
          allRejected = false
          bad.push(`${url} -> ${res.status}`)
        }
      } catch {
        allRejected = false
        bad.push(`${url} -> unreachable (is npm run dev running?)`)
      }
    }
    check(
      5,
      `all ${adminRoutes.length} admin route(s) reject a member session`,
      allRejected,
      bad.join('; ')
    )
  }
} finally {
  if (created) {
    await client.query('delete from public.submissions where id = $1', [created])
    console.log('\n  (probe row deleted)')
  }
  await client.end()
}

console.log(failures ? `\n${failures} FAILURE(S)\n` : '\nAll assertions passed.\n')
process.exit(failures ? 1 : 0)
